#!/bin/bash

# Setup Automated Maintenance Cron Jobs for IC Mesh
# Configures regular maintenance tasks to keep the system healthy

set -e

echo "🔧 IC Mesh Maintenance Scheduler Setup"
echo "===================================="
echo ""

# Get the absolute path to the ic-mesh directory
IC_MESH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAINTENANCE_SCRIPT="$IC_MESH_DIR/scripts/automated-maintenance.js"
LOG_DIR="$IC_MESH_DIR/logs"

echo "📁 IC Mesh Directory: $IC_MESH_DIR"
echo "🔧 Maintenance Script: $MAINTENANCE_SCRIPT"

# Create logs directory if it doesn't exist
mkdir -p "$LOG_DIR"

# Check if maintenance script exists
if [ ! -f "$MAINTENANCE_SCRIPT" ]; then
    echo "❌ Maintenance script not found: $MAINTENANCE_SCRIPT"
    exit 1
fi

# Make sure script is executable
chmod +x "$MAINTENANCE_SCRIPT"

# Backup existing crontab
echo "💾 Backing up existing crontab..."
if crontab -l > /tmp/crontab.backup 2>/dev/null; then
    echo "✅ Crontab backed up to /tmp/crontab.backup"
else
    echo "ℹ️  No existing crontab found"
    touch /tmp/crontab.backup
fi

# Create new crontab entries
echo "📝 Creating maintenance cron jobs..."

# Create temporary crontab file
cat > /tmp/ic-mesh-maintenance-cron << EOF
# IC Mesh Automated Maintenance Jobs
# Generated by setup-maintenance-cron.sh

# Full maintenance every 6 hours
0 */6 * * * cd "$IC_MESH_DIR" && node scripts/automated-maintenance.js >> logs/maintenance.log 2>&1

# Quick health check every 30 minutes
*/30 * * * * cd "$IC_MESH_DIR" && node scripts/automated-maintenance.js --health-only >> logs/health-check.log 2>&1

# Daily security audit at 3 AM
0 3 * * * cd "$IC_MESH_DIR" && node scripts/automated-maintenance.js --security-only >> logs/security-audit.log 2>&1

# Weekly deep cleanup on Sundays at 2 AM
0 2 * * 0 cd "$IC_MESH_DIR" && node scripts/automated-maintenance.js --deep-clean >> logs/deep-clean.log 2>&1

EOF

# Merge with existing crontab
cat /tmp/crontab.backup > /tmp/new-crontab
echo "" >> /tmp/new-crontab
cat /tmp/ic-mesh-maintenance-cron >> /tmp/new-crontab

# Ask user for confirmation
echo ""
echo "📋 Proposed cron schedule:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat /tmp/ic-mesh-maintenance-cron
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -p "Install these cron jobs? (y/n): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Install new crontab
    crontab /tmp/new-crontab
    echo "✅ Maintenance cron jobs installed successfully!"
    
    # Show current crontab for verification
    echo ""
    echo "📋 Current crontab:"
    crontab -l | grep -A 20 "IC Mesh Automated Maintenance"
    
    # Create log rotation config
    echo ""
    echo "🗂️  Setting up log rotation..."
    
    # Create logrotate config for IC Mesh logs
    sudo tee /etc/logrotate.d/ic-mesh > /dev/null << EOF
$LOG_DIR/*.log {
    daily
    missingok
    rotate 30
    compress
    notifempty
    copytruncate
}
EOF
    
    echo "✅ Log rotation configured"
    
    # Test maintenance script
    echo ""
    echo "🧪 Testing maintenance script (dry run)..."
    cd "$IC_MESH_DIR"
    node scripts/automated-maintenance.js --dry-run --verbose
    
    if [ $? -eq 0 ]; then
        echo "✅ Maintenance script test passed!"
    else
        echo "❌ Maintenance script test failed!"
        echo "Check the script and try again."
        exit 1
    fi
    
    # Create monitoring script
    cat > "$IC_MESH_DIR/scripts/check-maintenance-status.sh" << 'EOF'
#!/bin/bash

# Quick status check for IC Mesh maintenance
echo "🔍 IC Mesh Maintenance Status"
echo "============================"

LOGS_DIR="$(dirname "$0")/../logs"

# Check last maintenance run
if [ -f "$LOGS_DIR/maintenance.log" ]; then
    LAST_RUN=$(tail -1 "$LOGS_DIR/maintenance.log" | grep -o '\[.*\]' | head -1 || echo "Unknown")
    echo "📅 Last maintenance: $LAST_RUN"
else
    echo "❌ No maintenance log found"
fi

# Check for recent errors
if [ -f "$LOGS_DIR/maintenance.log" ]; then
    RECENT_ERRORS=$(tail -50 "$LOGS_DIR/maintenance.log" | grep -c "❌" || echo "0")
    if [ "$RECENT_ERRORS" -gt 0 ]; then
        echo "⚠️  Recent errors: $RECENT_ERRORS"
    else
        echo "✅ No recent errors"
    fi
fi

# Check disk usage
echo "💾 Disk usage:"
df -h "$LOGS_DIR" | tail -1 | awk '{print "   Available: " $4 " (" $5 " used)"}'

# Check cron status
echo "⏰ Cron jobs:"
crontab -l | grep -c "ic-mesh" | xargs echo "   IC Mesh jobs:"

echo ""
echo "📊 For detailed logs: tail -f $LOGS_DIR/maintenance.log"
EOF

    chmod +x "$IC_MESH_DIR/scripts/check-maintenance-status.sh"
    echo "✅ Monitoring script created: scripts/check-maintenance-status.sh"
    
    # Final instructions
    echo ""
    echo "🎉 Maintenance automation setup complete!"
    echo ""
    echo "📊 Monitor maintenance:"
    echo "   ./scripts/check-maintenance-status.sh"
    echo ""
    echo "📋 View logs:"
    echo "   tail -f logs/maintenance.log"
    echo "   tail -f logs/health-check.log"
    echo ""
    echo "🔧 Manual maintenance:"
    echo "   node scripts/automated-maintenance.js           # Full maintenance"
    echo "   node scripts/automated-maintenance.js --dry-run # Test only"
    echo ""
    echo "⏰ Scheduled maintenance will run:"
    echo "   • Every 6 hours: Full maintenance"
    echo "   • Every 30 minutes: Health checks"
    echo "   • Daily at 3 AM: Security audits"
    echo "   • Weekly on Sunday 2 AM: Deep cleanup"
    
else
    echo "❌ Installation cancelled."
    echo "💡 To install manually, run:"
    echo "   crontab -e"
    echo "   # Add the entries from /tmp/ic-mesh-maintenance-cron"
fi

# Cleanup
rm -f /tmp/ic-mesh-maintenance-cron /tmp/new-crontab